import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer";
import Side from "@/components/Side";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    {/* <Header/> */}
        <Side/>
        <div className="w-[90%] pt-10 mx-auto">
        {children}
        </div>
        {/* <Footer/> */}
    </>
      
  );
}
